global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
  
  - job_name: 'bank-login-metrics-final'
    static_configs:
      - targets: ['host.docker.internal:8000']